name: DynamicMob
version: '2.1'
main: me.linhyeok.DynamicMob
api-version: '1.21'
folia-supported: true
description: Custom mob configuration system
authors: [linhyeok]
website: https://discord.gg/astraspace